# Generated by Django 2.1.5 on 2020-06-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200625_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
