# Generated by Django 2.1.5 on 2020-08-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200708_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_of_create']},
        ),
    ]
