# Generated by Django 2.1.5 on 2020-09-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_auto_20200919_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='reply',
        ),
    ]
