# Generated by Django 2.1.5 on 2020-09-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_auto_20200919_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Topic'),
        ),
    ]
