# Generated by Django 3.1.1 on 2020-09-27 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0017_auto_20200921_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='Liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
