# Generated by Django 2.1.5 on 2020-06-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
