# Generated by Django 2.1.5 on 2020-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200618_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
