# Generated by Django 2.1.5 on 2020-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200619_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
