# Generated by Django 2.1.5 on 2020-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_of_realease',
            field=models.DateField(verbose_name='Data premiery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='Gatunek'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
