# Generated by Django 2.1.5 on 2020-06-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200622_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rating',
        ),
        migrations.AddField(
            model_name='rate',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
