# Generated by Django 2.1.5 on 2020-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200622_2102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
    ]
