# Generated by Django 2.1.5 on 2020-06-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200623_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('sender', 'person'), ('sender', 'movie')},
        ),
    ]
