# Generated by Django 2.1.5 on 2020-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
