# Generated by Django 2.1.5 on 2020-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200711_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='choice',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Twoja ocena'),
        ),
    ]
